[package]
name = "extend"
version = "1.2.0"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
edition = "2018"
categories = ["rust-patterns"]
description = "Create extensions for types you don't own with extension traits but without the boilerplate."
homepage = "https://github.com/davidpdrsn/extend"
keywords = ["extension", "trait"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/davidpdrsn/extend"

[dependencies]
syn = { version = "2", features = ["full", "extra-traits", "visit"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
trybuild = "1.0.17"
async-trait = "0.1.40"

[lib]
proc-macro = true
